
DELETE http://localhost:3001/api/persons/657ec4972c1848732aeb3b38

### 

DELETE http://localhost:3001/api/persons/657ec7db91ed9b297403e372


###

GET http://localhost:3001/api/persons

###

PUT http://localhost:3001/api/persons/64c39a42e1cd714a1b724070
Content-Type: application/json

{
    "name": "Moise Kongolo",
    "number": "0000111122"
}

###

GET http://localhost:3001/api/persons/658128adf56adb060d9f2a86

### 

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json 

{
    "name": "Cesare",
    "number": "777777777"
}

###

POST https://phonebook-11xn.onrender.com/api/persons HTTP/1.1
Content-Type: application/json 

{
    "name": "Nicole Mitonga",
    "number": "0842007675"
}

